package com.pwc.test.entities;

import java.sql.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.NonNull;
import lombok.RequiredArgsConstructor;
@Entity
//Entity specifies that this class should be mapped to the database table
@Table(name="orders")
/*
 * Table specifies the specific name that should be given to the table in
 * database that is dynamically generated by hibernate
 */
@Data
//Data is used to generate setters,getters,toString method
@NoArgsConstructor
//generates a 0-param constructor
@RequiredArgsConstructor
/*
 * generates a parameterized constructor with properties having
 * @NonNull annotation
 */
public class Order {

	@Id
	//Id specifies the primary key column in the table
	 @GeneratedValue(strategy = GenerationType.AUTO )
	//this works like a sequence which automatically generates the randon number
	private int orderid;
	
	@NonNull
	private boolean orderStatus;
	@NonNull
	private String order_name;
	
	
	
}
